### ISSUE TITLE
Generate JSON example body from schema object

### ISSUE THREAD

**Issue by kylef** [apiaryio/api-elements.js#100]

**Comment by alexylew** [comment]
Hey Kyle, am I correct that until this is implemented, I can't use my existing examples to generate tests and not have to hand-define all of our request bodies? If so, I'd love to contribute and help get this worked out.
 

I started looking through the codebase and what I'm stuck on is where we de-reference `$ref` objects into sub `DataStructure` objects, it looks like we just leave them as `ParseResult` objects with just the `element` field filled in. Is that the case? If so, can you point me in the right direction of actually dereferencing those objects; it looks like reference support is built out to some degree, so maybe I'm just missing something.

**Comment by alexylew** [comment]
@honzajavorek any guidance on this? I've got a quick and dirty solution working where I generate an example request body based on the example fields and pass a `samples` attribute up the chain, but can't push a branch to the remote.

**Comment by honzajavorek** [comment]
@alexylew Awesome! @kylef's traveling these days, so might not be so responsive. Would you be able to draft a Pull Request with the changes here? Fork the repository, push your branch with changes to the fork repository and then GitHub's UI should automatically offer you to create a PR to this (upstream) repository. Then we can have a discussion there specifically about your changes.

**Comment by divyanshmethi** [comment]
Hi @alexylew, Could you please post an example showing how your quick and dirty solution worked, because I am not able to figure out how you are doing it.
