### ISSUE TITLE
OAS 3 detection should not require quotes around openapi version number

### ISSUE THREAD

**Issue by kylef** [apiaryio/api-elements.js#118]
The detection logic for OpenAPI 3 relies on quotes being wrapped around the version. This was due to how Swagger 2 works (single 1.0 would become a number and not a string you ALWAYS had to wrap the version in a string). As OAS 3 versions are semantic and contain two dots they are a string always.

The logic is found at https://github.com/apiaryio/api-elements.js/blob/59e929ea9299891008a34d0f46ef1015ec815cc4/packages/fury-adapter-oas3-parser/lib/adapter.js#L13

Our detection logic should handle the case where quotes are not around the openapi version. Take the following example:

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: API Name
paths:
  /:
    get:
      summary: List
      responses:
        '204':
          description: empty response
```

**Comment by honzajavorek** [comment]
Looks like deckardcain has the same issue: https://github.com/apiaryio/deckardcain/blob/master/src/deckardcain.js#L11
