### ISSUE TITLE
Provide a "remote" Fury adapter

### ISSUE THREAD

**Issue by kylef** [apiaryio/api-elements.js#143]
As we provide an API (`https://api.apielements.org`) which can handle validation, parsing and serialisation we should offer this as an adapter itself so users can drop-in replace the adapters with remote parsing. It should be called `fury-adapter-remote`.

```js
const { Fury } = require('fury');
const FuryRemoteAdapter = require('fury-adapter-remote');

const fury = new Fury();
fury.use(new FuryRemoteAdapter({
  // the default value, but consumers should be able to override to use their own deployment
  url: 'https://api.apielements.org',

  // the collection of "parse", media types we want this
  // instance of the adapter to handle.
  // NOTE, this allows you to use the API for one media type but
  // another local adapter for another.
  parseMediaTypes: ['text/vnd.apiblueprint', 'application/oai.oas'],

  // the collection of "serialize", media types we want this
  // instance of the adapter to handle.
  serializeMediaTypes: ['text/vnd.apiblueprint'],
}));
```

```js
fury.validate(...);
fury.parse(...);
fury.serialise(...);
```

I'd suggest that the remote adapter use [`axios`](https://github.com/axios/axios) for talking to the API since is both Node and browser friendly and we're using it elsewhere. The adapter should perform POST requests to our public endpoints such as `/validate`, `/parse` and `/compose` using API Elements 1.0 content-type.

**Comment by char0n** [comment]
Yeah this would be great. If this is implemented we can use remote adapters for ApiaryUI in core app by configuring this at mount point. I'm working currently on creating a configuration point for this in ApiaryUI
