### ISSUE TITLE
How to easily access source map's line and column?

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/api-elements.js#159]
I'm trying to access source maps with their line and column attributes, which I was told by @kylef are now ready in all adapters (is #64 still relevant then?). I could not find any docs on the topic, so I was experimenting. I was pretty painful, but I managed to assemble this:

```js
const start = annotationElement.attributes.get('sourceMap').get(0).get(0).get(0);
console.log('start', start.attributes.get('line').toValue(), start.attributes.get('column').toValue());

const end = annotationElement.attributes.get('sourceMap').get(0).get(0).get(1);
console.log('end', end.attributes.get('line').toValue(), end.attributes.get('column').toValue());
```

Please tell me this is not the canocial way to do this and there's a simple way how to access it 🙏

**Comment by honzajavorek** [comment]
Oh, [there are docs](https://apielements.org/en/latest/element-definitions.html#source-map), I just didn't go to the right places. Still, is this the easiest way to access the data?

**Comment by kylef** [comment]
Source maps can span multiple lines and ranges, for example the following:

```
  a
  b
  c
```

Where there can be a source map entry in a single annotation which has multiple ranges, because an annotation could span multiple lines but not include indentation level. Therefore you should be supporting this case and not hard-coding getting index zeros. Here's an example (from https://github.com/w0rp/ale/issues/1749#issuecomment-406877142):

```apib
# API Name

## GET /

+ Response 200 (application/json)
    + Headers

        One: Two
        Three: Four
```

Drafter would emit:

```
warning: (10)  headers is expected to be a pre-formatted code block, every of its line indented by exactly 12 spaces or 3 tabs; line 8, column 9 - line 8, column 17; line 9, column 9 - line 9, column 20
```

Parse Result: https://dpaste.de/NY1P

**Comment by honzajavorek** [comment]
> line 8, column 9 - line 8, column 17; line 9, column 9 - line 9, column 20

I still might opt for cutting down the information contained. This is great as data for an editor to show annotations at the exact places, but I'm not sure it's as great for a human to read. At least I personally can't read it very well.

The information the issue is between line 8 column 9 and line 9 column 20 feels sufficient. I suppose it's not that often that the ranges contain bigger gaps, or is it?

**Comment by honzajavorek** [comment]
I'm thinking of something like this

```js
function compileAnnotation(annotationElement) {
  const sourceMapElement = annotationElement.attributes.get('sourceMap');

  const startAttributes = sourceMapElement.first.first.first.attributes;
  const endAttributes = sourceMapElement.last.last.last.attributes;

  return {
    type: annotationElement.classes.getValue(0),
    component: 'apiDescriptionParser',
    message: annotationElement.toValue(),
    location: [
      [startAttributes.get('line').toValue(), startAttributes.get('column').toValue()],
      [endAttributes.get('line').toValue(), endAttributes.get('column').toValue()],
    ],
  };
}
```
