### ISSUE TITLE
Add Snyk monitoring

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/api-elements.js#166]
Currently Snyk monitoring on the Dredd repo alerts about a vulnerability introduced through the Swagger adapter, but this repo doesn't indicate it.

<img width="259" alt="image" src="https://user-images.githubusercontent.com/283441/53174069-38511200-35e9-11e9-851d-0f6591189094.png">

<img width="829" alt="image" src="https://user-images.githubusercontent.com/283441/53174099-443cd400-35e9-11e9-83d1-b0d7592748f2.png">

**Comment by kylef** [comment]
![screenshot 2019-02-26 at 10 20 54](https://user-images.githubusercontent.com/44164/53405696-4a97cb00-39b0-11e9-9f48-49af28be2d8f.png)
