### ISSUE TITLE
JSON Schema formatting lost on conversion

### ISSUE THREAD

**Issue by nbrewster** [apiaryio/api-elements.js#218]
It looks like apiary_blueprint_convertor is discarding formatting (carriage returns ('\n'), spaces for indenting) - at least in the "validations" object. 

For example if my original blueprint (old format) has the following (see https://gist.github.com/nbrewster/11184760#file-test-old-blueprint-apib):

```
-- JSON Schema Validations --

POST /shopping-cart
{
    "request" :
        {
            "type": "object",
            "title": "request body schema",
            "properties": {
                "product": {
                    "type": "string"
                }
            }
        }
}
```

When I parse (with apiary-blueprint-parser) it, the AST still has the formatting (see https://gist.github.com/nbrewster/11184760#file-test-oldiblueprint_parsed-ast):

```
  "validations": [
    {
      "method": "POST",
      "url": "/shopping-cart",
      "body": "{\n    \"request\" :\n        {\n            \"type\": \"object\",\n            \"title\": \"request body schema\",\n            \"properties\": {\n                \"product\": {\n                    \"type\": \"string\"\n                }\n            }\n        }\n}"
    }
  ]
```

However after converting it with apiary_blueprint_convertor, the formatting is lost (see https://gist.github.com/nbrewster/11184760#file-converted-ast):

```
    "schema": "{\"type\":\"object\",\"title\":\"request body schema\",\"properties\":{\"product\":{\"type\":\"string\"}}}"
```

... and the resulting markdown (using matter_compiler --format json) is not too pretty:
### POST

Save new products in your shopping cart
- Request (application/json)
  - Body
    
    ```
    { "product":"1AB23ORM", "quantity": 2 }
    ```
  - Schema
    
    ```
    {"type":"object","title":"request body schema","properties":{"product":{"type":"string"}}}
    ```
- Response 201 (application/json)
  
  ```
  { "status": "created", "url": "/shopping-cart/2" }
  ```

I've confirmed that if I edit the converted AST to re-insert the carriage returns and indents, the resulting markdown produced by matter-compiler is nicely formatted.

**Comment by kylef** [comment]
This has been open for a while so apoligies. We've moved the conversion of Apiary Blueprint to API Blueprint into "Fury CLI" tool. I can confirm that this behaviour has been changed to pretty JSON print the schemas inside API Blueprint, for example:

```
$ npx fury packages/fury-adapter-apiary-blueprint-parser/test/fixtures/json-validations.txt --format text/vnd.apiblueprint
```

```apib
FORMAT: 1A

# API

## Group Example Resources

### /response-schema

#### GET [GET /response-schema]

+ Response 200 (application/json)

    + Body

            {
              "name": "Kyle"
            }

    + Schema

            {
              "type": "object"
            }
```

For more information on Fury CLI including installation and usage check out https://github.com/apiaryio/api-elements.js/tree/master/packages/fury-cli .
