### ISSUE TITLE
Parse Results should contain information about the input document

### ISSUE THREAD

**Issue by kylef** [apiaryio/api-elements.js#40]
Parse Results should contain a link to the source specification, the specific version that of the source document.

Something along the lines of:

```json
{
  "element": "parseResult",
  "meta": {
    "links": [
      {
      "element": "link",
      "meta": {
        "title": {
          "element": "string",
          "content": "application/vnd.openapi"
        },
        "description": {
          "element": "string",
          "content": "OpenAPI 3.0.0"
        }
      },
      "attributes": {
        "relation":  {
          "element": "string",
          "content": "< to be decided >"
        },
        "href":  {
          "element": "string",
          "content": "https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/3.0.0.md"
        }
      }
      }
    ]
  }
}

```

**Comment by opichals** [comment]
@kylef The description puts the `"application/vnd.openapi"` value to o `title` meta field. I'd say the field name should be more specific. Say `mimeType`?

**Comment by kylef** [comment]
> Something along the lines of

@opichals The design is TBD, I was just offering something to explore my idea and what information should be exposed.

The example is purely a valid element given the current specified API Elements 1.0 spec, there is no provision in the spec for relation specific attributes so that needs some thought.
