### ISSUE TITLE
Schema's properties aren't supported

### ISSUE THREAD

**Issue by kurko** [apiaryio/api-elements.js#446]
This looks like a bug. I couldn't find anywhere whether these are supported or not in Apiary. (I also had a hard time getting in contact with Oracle's support).

I have this:

```yaml
openapi: 3.0.0
# ... more specs here
components:
  schemas:
    PersonPersisted:
      title: PersonPersisted # <----- a warning is shown
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 0 # <----- a warning is shown
        email:
          type: string
          format: email # <----- a warning is shown
          minLength: 0 # <----- a warning is shown
        created_at:
          type: string
          description: ISO8601 format
          format: date-time # <----- a warning is shown
          example: '2020-04-13T17:13:27Z'
      description: 'A Person'
# ... more specs here
```

This is Apiary's editor warning:

<img width="463" alt="Screen Shot 2020-04-24 at 15 54 22" src="https://user-images.githubusercontent.com/70312/80247089-e1f3bf00-8643-11ea-9a83-29e3c63bef5c.png">

However, https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object clearly supports these properties.

Thoughts?

**Comment by kylef** [comment]
Apiary does not yet support these properties, and emits a warning that they are not supported so users are aware that these properties may not have any impact on parts of Apiary such as Dredd won't use them for validations, they won't be shown in Apiary documentation etc.

We provide a document in this repository [STATUS.md](https://github.com/apiaryio/api-elements.js/blob/master/packages/fury-adapter-oas3-parser/STATUS.md#schema-object) which contains the which properties are currently supported.

In terms of supporting some of the Schema Object properties in our parser and stack, it requires a bit of design to determine how we can translate these properties into the intermediatary format [API Elements](https://apielements.org/en/latest/) as its not a constraint based system like OpenAPI's Schema Object and cannot faciliate some schema concepts like `anyOf`, `not`, `oneOf` at this time. (https://apielements.org/en/latest/element-definitions.html#data-structure-element-types). These are the next steps.

**Comment by kurko** [comment]
Thanks for the updates.
