### ISSUE TITLE
Please add support for OpenAPI 3.0.0

### ISSUE THREAD

**Issue by baseten** [apiaryio/api-elements.js#47]
Would be super useful to have support for [OpenAPI 3.0.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md), this is the latest used by Swagger

**Comment by kylef** [comment]
@baseten OpenAPI 3 support has been added to Fury CLI 0.8.7, there are some open issues in the repository. Check out the [status page](https://github.com/apiaryio/api-elements.js/blob/b46e9ca2ac579b44ff650f412672deb33d33ba0a/packages/fury-adapter-oas3-parser/STATUS.md) to track the current supported functionality.
