### ISSUE TITLE
OAS3 path name regex is overly restrictive

### ISSUE THREAD

**Issue by nhynes** [apiaryio/api-elements.js#578]
This package defines a valid path name as
https://github.com/apiaryio/api-elements.js/blob/d566e232d26b0447bc599ee29f6fbecce85b8efb/packages/openapi3-parser/lib/parser/oas/parseParameterObject.js#L33
however, OAS3 says about [`name`](https://swagger.io/specification/#fixed-fields-10):
> If in is "path", the name field MUST correspond to a template expression occurring within the path field in the Paths Object. See Path Templating for further information.

but [path templating](https://swagger.io/specification/#path-templating) does not define any particular pattern.

Hence, the `pathNameAllowedRegex` can be as loose as `/[^ -~]/g`, but, at the very least, should not disallow dashes, the canonical url word separator character.

**Comment by kylef** [comment]
https://github.com/apiaryio/api-elements.js/issues/70 is tracking this so I will close this issue while link to that one.

For a bit of background and explanation of this behaviour:

The warning that the API Elements OpenAPI 3 parser emits via `pathNameAllowedRegex` is not that the variable name isn't permitted by OpenAPI. It is that it isn't supported in this parser and the surrounding Apiary tooling.

> 'Parameter Object' 'name' contains unsupported characters. Only alphanumeric characters are currently supported

Internally URI Template is used, which [imposes further restrictions](https://tools.ietf.org/html/rfc6570#section-2.3) on what this parser can allow given how [API Elements is defined](https://apielements.org/en/latest/element-definitions.html#templated-href-string). API Elements is the format this parser is converting to:

```
     variable-list =  varspec *( "," varspec )
     varspec       =  varname [ modifier-level4 ]
     varname       =  varchar *( ["."] varchar )
     varchar       =  ALPHA / DIGIT / "_" / pct-encoded
```

The solution proposed in https://github.com/apiaryio/api-elements.js/issues/70#issuecomment-444025799 is to internally percent encode unsupported values when representing these variables in URI Templates.
