### ISSUE TITLE
Support 'line' and 'column' in source map annotations

### ISSUE THREAD

**Issue by kylef** [apiaryio/api-elements.js#64]
We should emit 'line' and 'column' attributes in source map annotations as per the API Elements 1.0 specification.

Most of the work will be handled in `lib/parser/parseYAML`. We will need to update the code in `parseString` and similiar to discard the attributes while copying Source Map's over. I think in this case there should be a more generic function for specifically copying an elements source maps which has option to copy line/column which is only used by annotation creation (`lib/annotations.js`).

**Comment by honzajavorek** [comment]
This got closed, but I can't find line and column in the annotation source maps (v0.5.2).

<img width="490" alt="image" src="https://user-images.githubusercontent.com/283441/53403946-eb888500-39b4-11e9-976e-e3b2153632e2.png">

Is it something which is yet to be released?

**Comment by kylef** [comment]
@honzajavorek Do you have an example OpenAPI 3 document that is not producing the correct behaviour?

There are tests demonstrating the line/column numbers being present at https://github.com/apiaryio/api-elements.js/blob/fb11b3b6a931c0b5e43a9a104d5530283fffcaf3/packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json#L1268-L1327

**Comment by honzajavorek** [comment]
I've used `default` response to simulate a parser warning, but perhaps particularly this warning doesn't have source maps at all:

```json
{
      "element": "annotation",
      "meta": {
        "classes": {
          "element": "array",
          "content": [
            {
              "element": "string",
              "content": "warning"
            }
          ]
        }
      },
      "attributes": {},
      "content": "'Response Object' default responses unsupported"
    }
```

**Comment by honzajavorek** [comment]
So verified, `'Operation Object' contains invalid key 'foo'` warning has the source maps, but `'Response Object' default responses unsupported` does not, in the same document.

```yaml
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Title
paths:
  /:
    get:
      summary: Summary
      foo: null
      responses:
        "200": {}
        default: {}
```

**Comment by kylef** [comment]
I am seeing the sourcemaps and line numbers in one of the test fixtures for this particular warning at https://github.com/apiaryio/api-elements.js/blob/b4a6fd075d77c01d541f95f7309e66106351a12a/packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json#L906

The supplied document in your comment causes a single error which source maps:

> error: 'Response Object' is missing required property 'description' - line 11

**Comment by honzajavorek** [comment]
I'll check. Perhaps I pulled from dredd-transactions master, but forgot to `npm i` 😞

**Comment by honzajavorek** [comment]
Yeah, it's exactly the case 😞
